'use client';
import {useEffect,useState} from 'react';
import './styles.css';

type Block={id:number;type:string;label:string};
const MARKETS=[['1HZ100V','Volatility 100 (1s) Index'],['1HZ75V','Volatility 75 (1s) Index'],['1HZ50V','Volatility 50 (1s) Index'],['R_100','Volatility 100 Index'],['R_75','Volatility 75 Index']];
const palette=[['trade','Trade parameters'],['purchase','Purchase conditions'],['sell','Sell conditions'],['restart','Restart trading conditions']];

export default function Home(){
 const [screen,setScreen]=useState<'home'|'builder'|'chart'|'dashboard'>('home');
 const [market,setMarket]=useState('1HZ100V');const [ticks,setTicks]=useState<number[]>([]);const [balance,setBalance]=useState<any>(null);const [connected,setConnected]=useState(false);const [running,setRunning]=useState(false);const [message,setMessage]=useState('');
 useEffect(()=>{const s=new WebSocket('wss://api.derivws.com/trading/v1/options/ws/public');s.onopen=()=>s.send(JSON.stringify({ticks:market,subscribe:1,req_id:1}));s.onmessage=e=>{const x=JSON.parse(e.data);if(x.tick)setTicks(v=>[...v.slice(-79),Number(x.tick.quote)])};return()=>s.close()},[market]);
 useEffect(()=>{fetch('/api/account').then(r=>r.ok?r.json():null).then(j=>{const x=Array.isArray(j?.data)?j.data[0]:null;if(x){setBalance(x);setConnected(true)}}).catch(()=>{})},[]);
 const login=()=>{window.location.href='/api/login'};
 return <main className="dbot"><TopBar connected={connected} balance={balance} login={login}/>{screen==='home'&&<HomeScreen setScreen={setScreen}/>} {screen==='dashboard'&&<Dashboard balance={balance} market={market} running={running}/>} {screen==='builder'&&<Builder market={market} setMarket={setMarket} running={running} setRunning={setRunning} message={message} setMessage={setMessage}/>} {screen==='chart'&&<Chart market={market} setMarket={setMarket} ticks={ticks}/>}<BottomNav screen={screen} setScreen={setScreen}/>{screen==='builder'&&<RunBar running={running} onRun={()=>{setRunning(true);setMessage('Bot is running')}}/>}</main>
}
function TopBar({connected,balance,login}:any){return <header className="top"><button className="menu">☰</button><div className="dbot-logo"><span>DB</span><div><b>Deriv Bot</b><small>Automate Your Trades</small></div></div><div className="top-actions"><button className="account-pill">● {connected?'Demo account':'Guest'}</button><b>{balance?`${Number(balance.balance||0).toLocaleString(undefined,{minimumFractionDigits:2})} ${balance.currency||'USD'}`:'—'}</b><button className="login" onClick={login}>{connected?'Account':'Log in'}</button></div></header>}
function HomeScreen({setScreen}:any){return <section className="home-screen"><div className="home-copy"><h1>Load or build your bot</h1><p>Start with a saved bot, build one from scratch, or use a quick strategy.</p></div><div className="load-grid"><LoadCard icon="▣" title="Local" text="Open a bot saved on your device."/><LoadCard icon="◆" title="Google Drive" text="Open a bot from Google Drive."/><LoadCard icon="▦" title="Bot Builder" text="Build your strategy with visual blocks." action={()=>setScreen('builder')}/><LoadCard icon="⚡" title="Quick Strategy" text="Start quickly with predefined trading logic." action={()=>setScreen('builder')}/></div></section>}
function LoadCard({icon,title,text,action}:any){return <button className="load-card" onClick={action}><span>{icon}</span><strong>{title}</strong><small>{text}</small></button>}
function Dashboard({balance,market,running}:any){return <section className="dashboard"><div className="dash-title"><small>Dashboard</small><h1>{running?'Bot is running':'Bot is not running'}</h1></div><div className="dash-cards"><div><small>Account</small><b>{balance?'Demo account':'Not connected'}</b></div><div><small>Balance</small><b>{balance?`${Number(balance.balance||0).toFixed(2)} ${balance.currency||'USD'}`:'—'}</b></div><div><small>Market</small><b>{market}</b></div></div><div className="recent"><h2>Bot activity</h2><p>{running?'Your bot is currently running.':'No bot run yet.'}</p></div></section>}
function Builder({market,setMarket,running,setRunning,message,setMessage}:any){const [blocks,setBlocks]=useState<Block[]>([{id:1,type:'trade',label:'Trade parameters'},{id:2,type:'purchase',label:'Purchase conditions'},{id:3,type:'sell',label:'Sell conditions'},{id:4,type:'restart',label:'Restart trading conditions'}]);const [selected,setSelected]=useState(1);const add=(type:string)=>{const p=palette.find(x=>x[0]===type);if(p)setBlocks(v=>[...v,{id:Date.now(),type,label:p[1]}])};const remove=(id:number)=>setBlocks(v=>v.filter(b=>b.id!==id));return <section className="builder-page"><div className="builder-head"><div><h1>Bot Builder</h1><p>Build your trading bot using connected visual blocks.</p></div><div className="builder-tools"><button>↶</button><button>↷</button><button>−</button><button>＋</button><button>⌂</button></div></div><div className="builder-shell"><aside className="toolbox"><h3>Blocks</h3><p>Drag blocks into the workspace</p>{palette.map(([type,label])=><button className={`palette ${type}`} draggable onDragStart={e=>e.dataTransfer.setData('block',type)} onClick={()=>add(type)} key={type}><i/> {label}</button>)}<div className="toolbox-section"><b>Trade</b><button>▣ Market</button><button>◉ Contract</button><button>↕ Duration</button><button>＄ Stake</button></div><div className="toolbox-section"><b>Logic</b><button>if / then</button><button>Repeat</button><button>Number</button><button>Text</button></div></aside><div className="workspace" onDragOver={e=>e.preventDefault()} onDrop={e=>{const t=e.dataTransfer.getData('block');if(t)add(t)}}><div className="workspace-grid"/>{blocks.map((b,i)=><VisualBlock key={b.id} block={b} index={i} selected={selected===b.id} onSelect={()=>setSelected(b.id)} onDelete={()=>remove(b.id)} market={market} setMarket={setMarket}/>)}</div></div><div className="builder-status"><span className={running?'green':''}>● {running?'Bot is running':'Bot is not running'}</span>{message&&<small>{message}</small>}</div></section>}
function VisualBlock({block,index,selected,onSelect,onDelete,market,setMarket}:any){return <div className={`vblock ${block.type} ${selected?'selected':''}`} style={{marginLeft:(index%3)*22,marginTop:index===0?18:8}} onClick={onSelect}><div className="block-cap"><b>{block.label}</b><button onClick={e=>{e.stopPropagation();onDelete()}}>×</button></div>{block.type==='trade'?<div className="block-body"><label>Market<select value={market} onChange={e=>setMarket(e.target.value)}>{MARKETS.map(m=><option value={m[0]} key={m[0]}>{m[1]}</option>)}</select></label><div className="block-row"><label>Type<select><option>Rise</option><option>Fall</option></select></label><label>Duration<input defaultValue="1"/></label><label>Unit<select><option>Ticks</option><option>Seconds</option></select></label></div><label>Stake<input defaultValue="1.00"/></label></div>:<div className="block-body"><div className="socket"/><span>{block.type==='purchase'?'When purchase condition is true':block.type==='sell'?'When sell condition is true':'When restart condition is true'}</span></div>}<div className="connector top"/><div className="connector bottom"/></div>}
function Chart({market,setMarket,ticks}:any){const pts=ticks.length?ticks:[0];const min=Math.min(...pts),max=Math.max(...pts),range=max-min||1;const path=pts.map((v:number,i:number)=>`${(i/Math.max(pts.length-1,1))*100},${94-((v-min)/range)*88}`).join(' ');return <section className="chart-page"><div className="chart-toolbar"><select value={market} onChange={e=>setMarket(e.target.value)}>{MARKETS.map(m=><option value={m[0]} key={m[0]}>{m[1]}</option>)}</select><div className="timeframes"><button>1m</button><button>5m</button><button className="active">Tick</button><button>1h</button></div><b>{ticks.at(-1)?.toFixed(2)||'—'}</b></div><div className="smart-chart"><div className="chart-grid"/><svg viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points={path}/></svg><div className="price-label">{ticks.at(-1)?.toFixed(2)||'—'}</div></div></section>}
function RunBar({running,onRun}:any){return <div className="runbar"><button className="run-button" onClick={onRun}>▶ Run</button><div><b>{running?'Bot is running':'Bot is not running'}</b><small>{running?'Trading automation active':'Ready to run your bot'}</small></div></div>}
function BottomNav({screen,setScreen}:any){return <nav className="bottom-nav"><button className={screen==='home'?'active':''} onClick={()=>setScreen('home')}><span>⌂</span>Home</button><button className={screen==='dashboard'?'active':''} onClick={()=>setScreen('dashboard')}><span>▥</span>Dashboard</button><button className={screen==='builder'?'active':''} onClick={()=>setScreen('builder')}><span>▦</span>Bot Builder</button><button className={screen==='chart'?'active':''} onClick={()=>setScreen('chart')}><span>⌁</span>Chart</button></nav>}
